; generated by test fixture
; printer_model = COREONE
; filament_type = PLA;PLA
; nozzle_diameter = 0.4
; total toolchanges = 868
; estimated printing time (normal mode) = 5h 11m 3s
M73 P0 R0
G21
G90
M83
G1 Z0.2 F720
G1 X0 Y0 E1 F1200
; prusaslicer_config = begin
; prusaslicer_config = end
